; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F446RE]
platform = ststm32
board = genericSTM32F446RE
framework = stm32cube

;undefines default build flags
build_unflags = 
    -Os                     ;undefines preset compiler optimization lvl
    -DUSE_HAL_DRIVER        ;don't use HAL librarys

;defines new needed build flags
build_flags = 
    ;-DSTM32F334x8          ;already set by default
    -DUSE_FULL_LL_DRIVER    ;use ll librarys
    ;-DUSE_FULL_ASSERT      ;use stm32 assert
    -O0                     ;defines optimization lvl 0
    -std=c99                ;use c99 standard (newer standards also possible, see gcc compiler options)
    ; -v                     ;enables verbose output

;doesn't change core clock configuration, just tells PIO the configured core clock (not necessarily needed)
board_build.f_cpu = 64000000L
